#ifndef MLX_CONF_INPUT_H
# define MLX_CONF_INPUT

# define INPUT_COLOR_ENABLED 0xFF000000
# define INPUT_COLOR_DISABLED 0xFF000000

# define INPUT_SIZE_CHAR_Y 30
# define INPUT_SIZE_CHAR_X 15

#endif
