#ifndef MLX_CONF_IMG_H
# define MLX_CONF_IMG_H

# define ID_IMG_MENU_CADRE 0
# define ID_IMG_MENU_CADRE_LIGHTNING 1
# define ID_IMG_MENU_CADRE_LOGO 2

# define ID_IMG_BTN_LOAD 3
# define ID_IMG_BTN_LOAD_OVER 4
# define ID_IMG_BTN_LOAD_CLICK 5
# define ID_IMG_BTN_SAVE 6
# define ID_IMG_BTN_SAVE_OVER 7
# define ID_IMG_BTN_SAVE_CLICK 8

# define BOT_BTN_X_DECALLAGE 1

# define ID_IMG_BTN_SCENE 9
# define ID_IMG_BTN_SCENE_OVER 10
# define ID_IMG_BTN_SCENE_CLICK 11
# define ID_IMG_BTN_OBJECT 12
# define ID_IMG_BTN_OBJECT_OVER 13
# define ID_IMG_BTN_OBJECT_CLICK 14
# define ID_IMG_BTN_SPOT 15
# define ID_IMG_BTN_SPOT_OVER 16
# define ID_IMG_BTN_SPOT_CLICK 17
# define ID_IMG_BTN_CAMERA 18
# define ID_IMG_BTN_CAMERA_OVER 19
# define ID_IMG_BTN_CAMERA_CLICK 20

# define ID_IMG_BTN_ARROW_RIGHT_OFF 21
# define ID_IMG_BTN_ARROW_RIGHT 22
# define ID_IMG_BTN_ARROW_RIGHT_OVER 23
# define ID_IMG_BTN_ARROW_RIGHT_CLICK 24

# define ID_IMG_BTN_ARROW_LEFT_OFF 25
# define ID_IMG_BTN_ARROW_LEFT 26
# define ID_IMG_BTN_ARROW_LEFT_OVER 27
# define ID_IMG_BTN_ARROW_LEFT_CLICK 28

# define ID_IMG_PREVIEW_NO_IMG 29
# define ID_IMG_PREVIEW 30
# define ID_IMG_PREVIEW_OVER 31
# define ID_IMG_PREVIEW_CLIC 32

# define ID_IMG_LOADING 33

# define ID_IMG_BTN_SCENE_OFF 34
# define ID_IMG_BTN_OBJECT_OFF 35
# define ID_IMG_BTN_SPOT_OFF 36
# define ID_IMG_BTN_CAMERA_OFF 37


# define ID_IMG_BTN_EDIT_ADD_OFF 38
# define ID_IMG_BTN_EDIT_MOD_OFF 39
# define ID_IMG_BTN_EDIT_DEL_OFF 40

# define ID_IMG_BTN_SELECTED 41

# define ID_IMG_BTN_EDIT_ADD 42
# define ID_IMG_BTN_EDIT_ADD_OVER 43
# define ID_IMG_BTN_EDIT_ADD_CLICK 44

# define ID_IMG_MENU_ADD_SCENE_BOX 45

# define ID_IMG_BTN_SCENE_ADD_OK 46
# define ID_IMG_BTN_SCENE_ADD_OK_OVER 47
# define ID_IMG_BTN_SCENE_ADD_OK_CLICK 48

# define ID_IMG_BTN_SCENE_ADD_CANCEL 49
# define ID_IMG_BTN_SCENE_ADD_CANCEL_OVER 50
# define ID_IMG_BTN_SCENE_ADD_CANCEL_CLICK 51

# define ID_MAX_AUTO_INIT 51

#endif
