#ifndef MLX_CONF_IMG_H
# define MLX_CONF_IMG_H

# define IMENU_CADRE 0
# define IMENU_CADRE_LIGHTNING 1
# define IMENU_CADRE_LOGO 2

# define IB_LOAD 3
# define IB_LOAD_OVER 4
# define IB_LOAD_CLICK 5
# define IB_SAVE 6
# define IB_SAVE_OVER 7
# define IB_SAVE_CLICK 8

# define BOT_BTN_X_DECALLAGE 1

# define IB_SCENE 9
# define IB_SCENE_OVER 10
# define IB_SCENE_CLICK 11
# define IB_OBJECT 12
# define IB_OBJECT_OVER 13
# define IB_OBJECT_CLICK 14
# define IB_SPOT 15
# define IB_SPOT_OVER 16
# define IB_SPOT_CLICK 17
# define IB_CAMERA 18
# define IB_CAMERA_OVER 19
# define IB_CAMERA_CLICK 20

# define IB_ARROW_RIGHT_OFF 21
# define IB_ARROW_RIGHT 22
# define IB_ARROW_RIGHT_OVER 23
# define IB_ARROW_RIGHT_CLICK 24

# define IB_ARROW_LEFT_OFF 25
# define IB_ARROW_LEFT 26
# define IB_ARROW_LEFT_OVER 27
# define IB_ARROW_LEFT_CLICK 28

# define IMG_PREVIEW_NO_IMG 29
# define IMG_PREVIEW 30
# define IMG_PREVIEW_OVER 31
# define IMG_PREVIEW_CLIC 32

# define IMG_LOADING 33

# define IB_SCENE_OFF 34
# define IB_OBJECT_OFF 35
# define IB_SPOT_OFF 36
# define IB_CAMERA_OFF 37

# define IB_E_ADD_OFF 38
# define IB_E_SWITCH_OFF 39
# define IB_E_DEL_OFF 40

# define IB_SELECTED 41

# define IB_E_ADD 42
# define IB_E_ADD_OVER 43
# define IB_E_ADD_CLICK 44

# define IMENU_ADD_SCENE_BOX 45

# define IB_SCENE_ADD_OK 46
# define IB_SCENE_ADD_OK_OVER 47
# define IB_SCENE_ADD_OK_CLICK 48

# define IB_E_MOD_OFF 49
# define IB_E_MOD 50
# define IB_E_MOD_OVER 51
# define IB_E_MOD_CLICK 52

# define IB_E_SWITCH 53
# define IB_E_SWITCH_OVER 54
# define IB_E_SWITCH_CLICK 55

# define IMENU_EDIT_SCENE_BOX 56

# define IB_E_DEL 57
# define IB_E_DEL_OVER 58
# define IB_E_DEL_CLICK 59

# define IMENU_EDIT_SCENE_BOX_DEL 60

# define IB_SCENE_DEL_OK 61
# define IB_SCENE_DEL_OK_OVER 62
# define IB_SCENE_DEL_OK_CLICK 63

# define IB_SCENE_DEL_CANCEL 64
# define IB_SCENE_DEL_CANCEL_OVER 65
# define IB_SCENE_DEL_CANCEL_CLICK 66

# define ID_MAX_AUTO_INIT 67

#endif
